site_name: Sailfish-v0.8 Documentation
site_url: https://clemson-cal.github.io/sfdocs/

# Search and Plugin Configuration
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
  - minify:
      minify_html: true

# Site Navigation
nav:
  - Home: index.md
  - Overview:
    - Installation & Setup: setups.md
    - Basic Configuration: definitions.md
    - Preset Configurations: presets.md
  - Configuration Reference:
    - Complete Parameter Guide: configuration.md
    - Science Products & Timeseries: products-timeseries.md
  - Code Examples: code-examples.md
  - Tutorials:
    - Tutorial: tutorial.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: simple/fishshell
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    # Search features
    - search.highlight
    - search.suggest
    - search.share
  palette:
    # Default to Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: black
      accent: cyan

    # Light Mode (secondary option)
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: grey
      accent: deep orange


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/clemson-cal/sailfish-v0.8/
      name: GitHub Repository
  generator: false

copyright: Copyright &copy; 2025 Clemson-CAL      
