site_name: Sailfish-v0.8 Documentation
site_url: https://akhiln.github.io/sfdocs/
theme:
  name: material
  font:
    text: Lato
    code: Fira Code
  icon:
    logo: simple/fishshell
  features:
    - navigation.tracking
    - navigation.footer
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.tabs.link
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep purple


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: simple/github
      link: https://github.com/clemson-cal/sailfish-v0.8/

copyright: Copyright &copy; 2025 Clemson-CAL      
